env:
  browser: true
  es2021: true
  jest: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 6
  sourceType: commonjs
plugins:
  - '@typescript-eslint'
rules: { 'no-console': 'warn' }
ignorePatterns: ['dist', 'node_modules', 'coverage']
